---
title: "The Importance of the Offensive Line"
author: "Brendan Routh"
date: "1/15/2018"
output:
  pdf_document: default
  html_document: default
---


```{r warning=FALSE, message=FALSE}
library(rvest)
library(methods)
library(tidyverse)

urlT17 <- 'http://www.nfl.com/stats/categorystats?tabSeq=2&offensiveStatisticCategory=RUSHING&conference=ALL&role=TM&season=2017&seasonType=REG&d-447263-s=RUSHING_YARDS_PER_GAME_AVG&d-447263-o=2&d-447263-n=1'

urlT16 <- 'http://www.nfl.com/stats/categorystats?archive=true&conference=null&role=TM&offensiveStatisticCategory=RUSHING&defensiveStatisticCategory=null&season=2016&seasonType=REG&tabSeq=2&qualified=false&Submit=Go'

urlT15 <- 'http://www.nfl.com/stats/categorystats?archive=true&conference=null&role=TM&offensiveStatisticCategory=RUSHING&defensiveStatisticCategory=null&season=2015&seasonType=REG&tabSeq=2&qualified=false&Submit=Go'

urlT14 <- 'http://www.nfl.com/stats/categorystats?archive=true&conference=null&role=TM&offensiveStatisticCategory=RUSHING&defensiveStatisticCategory=null&season=2014&seasonType=REG&tabSeq=2&qualified=false&Submit=Go'

urlD17 <- 'https://www.pro-football-reference.com/years/2017/draft.htm'

urlD16 <- 'https://www.pro-football-reference.com/years/2016/draft.htm'

urlD15 <- 'https://www.pro-football-reference.com/years/2015/draft.htm'

urlD14 <- 'https://www.pro-football-reference.com/years/2014/draft.htm'

fetch_table <- function(url)
{
  tables <- url %>%
    read_html() %>%
    html_nodes("table")
  
  TableX = html_table(tables[[1]], fill = TRUE, header = TRUE)
  
  return(TableX)
}

T17 <- fetch_table(urlT17)
T16 <- fetch_table(urlT16)
T15 <- fetch_table(urlT15)
T14 <- fetch_table(urlT14)

D17 <- fetch_table(urlD17)
D16 <- fetch_table(urlD16)
D15 <- fetch_table(urlD15)
D14 <- fetch_table(urlD14)
```


```{r warning=FALSE, message=FALSE}
correct_header <- function(df)
{
  colnames(df) = df[1, ]
  df = df[-1, ] 
  return(df)
}

D17 <- correct_header(D17)
D16 <- correct_header(D16)
D15 <- correct_header(D15)
D14 <- correct_header(D14)

correct_col_names <- function(df)
{
  colnames(df)[15] <- 'Pass_Attempts'
  colnames(df)[16] <- 'Pass_Yds'
  colnames(df)[17] <- 'Pass_TDs'
  colnames(df)[18] <- 'Pass_Ints'
  colnames(df)[19] <- 'Rush_Attempts'
  colnames(df)[20] <- 'Rush_Yds'
  colnames(df)[21] <- 'Rush_TDs'
  colnames(df)[23] <- 'Rec_Yds'
  colnames(df)[24] <- 'Rec_TDs'
  colnames(df)[29] <- 'College_Stats'
  return(df)
}

D17 <- correct_col_names(D17)
D16 <- correct_col_names(D16)
D15 <- correct_col_names(D15)
D14 <- correct_col_names(D14)

#Only the first three rounds
D17<- D17 %>% select(Rnd, Tm, Pos) %>% filter(Rnd == 1 | Rnd == 2 | Rnd == 3)
D16<- D16 %>% select(Rnd, Tm, Pos) %>% filter(Rnd == 1 | Rnd == 2 | Rnd == 3)
D15<- D15 %>% select(Rnd, Tm, Pos) %>% filter(Rnd == 1 | Rnd == 2 | Rnd == 3)
D14<- D14 %>% select(Rnd, Tm, Pos) %>% filter(Rnd == 1 | Rnd == 2 | Rnd == 3)
```


```{r warning=FALSE, message=FALSE}

ram_charger <- function(df)
{
  d_rams <- df %>% filter(Tm == "LAR" | Tm == "STL")
  d_rams <- d_rams %>% mutate(Tm = ifelse(Tm == "STL", "LAR", "LAR"))

  d_chargers <- df %>% filter(Tm == "LAC" | Tm == "SDG")
  d_chargers <- d_chargers %>% mutate(Tm = ifelse(Tm == "SDG", "LAC", "LAC"))

  df <- df %>% filter(Tm != "LAC" & Tm != "SDG" & Tm != "LAR" & Tm != "STL")

  df <- df %>% full_join(d_rams, by=c('Rnd', 'Tm', 'Pos')) %>% full_join(d_chargers, by=c('Rnd', 'Tm', 'Pos'))
  
  return(df)
}

D17 <- ram_charger(D17)
D16 <- ram_charger(D16)
D15 <- ram_charger(D15)
D14 <- ram_charger(D14)
```

```{r warning=FALSE, message=FALSE}
draft_four_year <- D17 %>% 
              full_join(D16,by=c('Rnd','Tm', 'Pos'))%>%
              full_join(D15,by=c('Rnd','Tm', 'Pos'))%>%
              full_join(D14,by=c('Rnd','Tm', 'Pos'))
```

```{r warning=FALSE, message=FALSE}

fullFromAbrv <-function(x) {
   
  team.codes<-data.frame(

  abrv <- as.factor(c("ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL", "DEN", "DET",    "GNB", "HOU", "IND", "JAX", "KAN", "LAC", "LAR", "MIA", "MIN", "NWE", "NOR", "NYG", "NYJ", "OAK",   "PHI", "PIT", "SEA", "SFO", "TAM", "TEN", "WAS")),

  full <- as.factor(c("Arizona Cardinals", "Atlanta Falcons", "Baltimore Ravens", "Buffalo Bills",    "Carolina Panthers", "Chicago Bears", "Cincinnati Bengals", "Cleveland Browns", "Dallas Cowboys",   "Denver Broncos", "Detroit Lions", "Green Bay Packers", "Houston Texans", "Indianapolis Colts",     "Jacksonville Jaguars", "Kansas City Chiefs", "Los Angeles Chargers", "Los Angeles Rams","Miami     Dolphins", "Minnesota Vikings", "New England Patriots", "New Orleans Saints", "New York Giants",    "New York Jets", "Oakland Raiders", "Philadelphia Eagles", "Pittsburgh Steelers", "San Francisco    49ers", "Seattle Seahawks", "Tampa Bay Buccaneers", "Tennessee Titans", "Washington Redskins"))
  )
  
  team.x<-data.frame(abrv=x)
   
  refac.x<-team.codes$full[match(team.x$abrv,team.codes$abrv)]
     
  return(refac.x)
}

draft_four_year$Tm <- fullFromAbrv(draft_four_year$Tm)
```


```{r warning=FALSE, message=FALSE}
draft_four_year <- draft_four_year %>% group_by(Tm) %>% mutate(o_line = ifelse(Pos == 'T' | Pos == 'G' | Pos == 'OL' | Pos == 'C',1,0)) %>% summarise(num_o_line = sum(o_line))
```

```{r warning=FALSE, message=FALSE}
T17 <- T17 %>% select('Team', 'Yds/G', 'Pts/G') %>% mutate(Season = '17')
T16 <- T16 %>% select('Team', 'Yds/G', 'Pts/G') %>% mutate(Season = '16')
T15 <- T15 %>% select('Team', 'Yds/G', 'Pts/G') %>% mutate(Season = '15')
T14 <- T14 %>% select('Team', 'Yds/G', 'Pts/G') %>% mutate(Season = '14')

names(T17)[names(T17) == 'Yds/G'] = 'Yds_G'; names(T17)[names(T17) == 'Pts/G'] = 'Pts_G'
names(T16)[names(T16) == 'Yds/G'] = 'Yds_G'; names(T16)[names(T16) == 'Pts/G'] = 'Pts_G' 
names(T15)[names(T15) == 'Yds/G'] = 'Yds_G'; names(T15)[names(T15) == 'Pts/G'] = 'Pts_G'
names(T14)[names(T14) == 'Yds/G'] = 'Yds_G'; names(T14)[names(T14) == 'Pts/G'] = 'Pts_G'
```

```{r warning=FALSE, message=FALSE}
four_year <- T17 %>% 
              full_join(T16,by=c('Team', 'Yds_G', 'Pts_G', 'Season'))%>%
              full_join(T15,by=c('Team', 'Yds_G', 'Pts_G', 'Season'))%>%
              full_join(T14,by=c('Team', 'Yds_G', 'Pts_G', 'Season'))
```

```{r warning=FALSE, message=FALSE}
four_year <- as.data.frame(four_year)

rams <- four_year %>% filter(Team == "Los Angeles Rams" | Team == "St. Louis Rams")
rams <- rams %>% mutate(Team = ifelse(Team == "St. Louis Rams", "Los Angeles Rams", "Los Angeles Rams"))

chargers <- four_year %>% filter(Team == "Los Angeles Chargers" | Team == "San Diego Chargers")
chargers <- chargers %>% mutate(Team = ifelse(Team == "San Diego Chargers", "Los Angeles Chargers", "Los Angeles Chargers"))

four_year <- four_year %>% filter(Team != "Los Angeles Chargers" & Team != "San Diego Chargers" & Team != "Los Angeles Rams" & Team != "St. Louis Rams")

four_year <- four_year %>% full_join(rams, by=c('Team', 'Yds_G', 'Pts_G', 'Season')) %>% full_join(chargers, by=c('Team', 'Yds_G', 'Pts_G', 'Season'))

four_year <- four_year %>% group_by(Team) %>% summarise(yards_avg = mean(Yds_G), points_avg = mean(Pts_G))
```